services:
  redis:
    image: redis:7-alpine
    container_name: ai_learning-redis-1
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: ai_learning-fastapi-1
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RAG_OPENAI_BASE_URL=http://host.docker.internal:11434/v1
      - RAG_EMBED_MODEL_PATH=/models/text2vec-base-chinese
      - RAG_REDIS_URL=redis://redis:6379/0
      - RAG_CELERY_BROKER_URL=redis://redis:6379/0
      - RAG_CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - ./data/chroma_db:/app/data/chroma_db
      - D:/models:/models:ro
      - ./uploads:/app/uploads

  celery-worker:
    build: .
    container_name: ai_learning-celery-worker-1
    env_file:
      - .env
    environment:
      - RAG_OPENAI_BASE_URL=http://host.docker.internal:11434/v1
      - RAG_EMBED_MODEL_PATH=/models/text2vec-base-chinese
      - RAG_REDIS_URL=redis://redis:6379/0
      - RAG_CELERY_BROKER_URL=redis://redis:6379/0
      - RAG_CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - fastapi
    command: celery -A ai_rag.tasks.celery_app worker --loglevel=info --concurrency=1 --pool=solo
    volumes:
      - ./data/chroma_db:/app/data/chroma_db
      - D:/models:/models:ro
      - ./uploads:/app/uploads
